<a href="https://colab.research.google.com/github/pcsilcan/dm/blob/master/20202/dm_20202_0201_preprocessing_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Scikit-learn
## Standarization

In [1]:
import numpy as np
from sklearn import preprocessing

In [2]:
X_train = np.array([[  1., -1.,  2. ],
                    [  2.,  0.,  0. ],
                    [  0.,  1., -1. ]])
X_scaled = preprocessing.scale(X_train)

print(X_scaled)

[[ 0.         -1.22474487  1.33630621]
 [ 1.22474487  0.         -0.26726124]
 [-1.22474487  1.22474487 -1.06904497]]


In [4]:
print(X_scaled.mean(axis=0))
print(X_scaled.std(axis=0))

[0. 0. 0.]
[1. 1. 1.]


In [5]:
scaler = preprocessing.StandardScaler().fit(X_train)
scaler

StandardScaler(copy=True, with_mean=True, with_std=True)

In [6]:
print(scaler.mean_)
print(scaler.scale_)

[1.         0.         0.33333333]
[0.81649658 0.81649658 1.24721913]


In [7]:
scaler.transform(X_train)

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

## Normalization

In [10]:
X = [[  1., -1.,  2. ],
     [  2.,  0.,  0. ],
     [  0.,  1., -1. ]]
X_normalized = preprocessing.normalize(X, norm='l2')
print(X_normalized)

[[ 0.40824829 -0.40824829  0.81649658]
 [ 1.          0.          0.        ]
 [ 0.          0.70710678 -0.70710678]]


In [11]:
normalizer = preprocessing.Normalizer().fit(X)
print(normalizer)

Normalizer(copy=True, norm='l2')


In [12]:
normalizer.transform(X)

array([[ 0.40824829, -0.40824829,  0.81649658],
       [ 1.        ,  0.        ,  0.        ],
       [ 0.        ,  0.70710678, -0.70710678]])

## Missing values

In [17]:
from sklearn.impute import SimpleImputer

In [24]:
imp = SimpleImputer(missing_values=np.nan,
                    strategy='mean')

imp.fit([[1, 2], [np.nan, 3], [7, 6]])

SimpleImputer(add_indicator=False, copy=True, fill_value=None,
              missing_values=nan, strategy='mean', verbose=0)

In [25]:
X = [[np.nan,       2],
     [     6,  np.nan],
     [     7,       6]]
print(imp.transform(X))

[[4.         2.        ]
 [6.         3.66666667]
 [7.         6.        ]]


In [27]:
import scipy.sparse as sp

In [28]:
X = sp.csc_matrix([[1, 2], [0, 3], [7, 6]])
print(X)

  (0, 0)	1
  (2, 0)	7
  (0, 1)	2
  (1, 1)	3
  (2, 1)	6


In [30]:
imp = SimpleImputer(missing_values=np.nan, strategy='mean')
imp.fit(X)

SimpleImputer(add_indicator=False, copy=True, fill_value=None,
              missing_values=nan, strategy='mean', verbose=0)

In [32]:
X_test = sp.csc_matrix([[0, 2], [6, 0], [7, 6]])
print(X_test)
print(imp.transform(X_test))

  (1, 0)	6
  (2, 0)	7
  (0, 1)	2
  (2, 1)	6
  (1, 0)	6.0
  (2, 0)	7.0
  (0, 1)	2.0
  (2, 1)	6.0
